version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amore-eterno-app
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
